title: "Contact - Francisco Ossian"
description: "Entre em contato com Francisco Ossian para projetos de tecnologia e desenvolvimento web."
keywords: "Francisco Ossian, Contato, Tecnologia, Desenvolvimento Web"

OG:
  title: "Contato - Francisco Ossian"
  description: "Entre em contato com Francisco Ossian para projetos de tecnologia e desenvolvimento web."
  url: "https://www.foln.dev/contact"
  keywords: "Francisco Ossian, Contato, Tecnologia, Desenvolvimento Web"
