title: "Projetos - Francisco Ossian"
description: "Explore os projetos desenvolvidos por Francisco Ossian nas áreas de tecnologia e desenvolvimento web."
keywords: "Francisco Ossian, Projetos, Desenvolvimento Web, Tecnologia"

OG:
  title: "Projetos - Francisco Ossian"
  description: "Explore os projetos desenvolvidos por Francisco Ossian nas áreas de tecnologia e desenvolvimento web."
  url: "https://www.foln.dev/projetos"
  type: "website"
  keywords: "Francisco Ossian, Projetos, Desenvolvimento Web, Tecnologia"
