title: "Anotações de um estudante sobre compiladores"
categories:
  - "Tecnologia"
  - "Desenvolvimento Web"
description: "Anotações de Francisco Ossian sobre o tema de compiladores"
keywords: "Compiladores, Programação, Interpretadores, Ciências da Computações"

OG:
  title: "Blog - Anotações de um estudante sobre compiladores"
  description: "Anotações de Francisco Ossian sobre o tema de compiladores"
  url: "https://www.foln.dev/blog/Compilers-My-Notes"
  type: "blog"
  keywords: "Compiladores, Programação, Interpretadores, Ciências da Computações"