title: Anotações de um estudante sobre c++
  - Tecnologia
  - Desenvolvimento
  - C++
description: "Anotações de Francisco Ossian sobre a linguagem C++"
keywords: "Programação, Ciências da Computações, C++"

OG:
  title: "Blog - Anotações de um estudante sobre C++"
  description: "Anotações de Francisco Ossian sobre C++"
  url: "https://www.foln.dev/blog/Cpp-Study-Notes"
  type: "article"
  keywords: "Programação, Ciências da Computações, C++"