title: "Sobre Mim"
categories:
  - "Tecnologia"
  - "Desenvolvimento Web"
description: "Conheça mais sobre Francisco Ossian, estudante de Ciência da Computação na UECE e desenvolvedor Front-End apaixonado por tecnologia."
keywords: "Francisco Ossian, Tecnologia, Desenvolvimento Web, Ciência da Computação, Front-End, Portfolio"

OG:
  title: "Sobre Mim - Francisco Ossian"
  description: "Conheça mais sobre Francisco Ossian, estudante de Ciência da Computação na UECE e desenvolvedor Front-End apaixonado por tecnologia."
  url: "https://www.foln.dev/about"  # URL da sua página /about
  type: "profile"
  keywords: "Francisco Ossian, Tecnologia, Desenvolvimento Web, Ciência da Computação, Front-End, Portfolio"

teste2: 'klmdlk'